version: '3.8'
services:
  backend:
    build: 
      dockerfile: Dockerfile
    container_name: go-backend
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=password
    ports:
      - "${API_PORT}:8888"
    networks:
      - db-network
  db:
    image: postgres:alpine
    container_name: backend-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=backend_go
    ports:
      - ${DB_POSTGRE_DB}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-network
volumes:
  db-data:
networks:
  db-network:

